### PR TITLE
lesson-2-1 CTD numberGuessing Game

### PR DESCRIPTION
**Pull request by leipei92**
Refactoring old school class components into function react components.

### CODE REVIEW

**Review by JoHeyJo — APPROVED** [review]
Nicely done! A few things that should be addressed. App should also be refactored into a function component (Consistency in coding style is important). This was a slight oversight in the instructions. Also, there is a small bug in the UI. All data submission should be controlled with a `form` tag. This causes a small bug in the UI. Otherwise, fantastic job! Approving for merge.

**Comment by leipei92** [comment]
Thank you for the feedback! So to fix the bug I need to add `<form>` tags, is that correct?

**Comment by JoHeyJo** [comment]
Yes. You would wrap all associated `input` and `label` tags inside the `form` tag.

**Comment by leipei92** [comment]
Gotcha! All done now. Thanks:)

**Pull request merged**
